"""End-to-end flashcard generation orchestration."""

import json
from typing import Any, Dict, List, Optional

from ...core.config import FLASHCARD_COUNT_MAX, FLASHCARD_COUNT_MIN
from ...db.postgres import (
    get_lecture,
    get_lecture_study_materials,
    get_previous_flashcard_questions,
)
from ..embeddings import embed_texts
from ..study_materials import generate_key_points as generate_key_points_for_lecture
from .constants import CANDIDATE_COUNT, FINAL_COUNT_DEFAULT
from .generation import (
    expand_keypoint_to_answer,
    fill_missing_flashcards,
    generate_flashcard_candidates,
    generate_flashcards_from_chunks,
    get_chunks_per_keypoint,
    prepare_context_for_chunks,
)
from .selection import deduplicate_candidates, select_final_flashcards
from .validation import (
    answer_echoes_question,
    compute_quality_score,
    normalize_text,
    validate_flashcard,
    validate_flashcard_lenient,
)


def generate_flashcards_v2(
    lecture_id: int,
    user_id: Optional[int] = None,
    strategy: str = "keypoints_v1",
    regenerate: bool = False,
    target_count: Optional[int] = None,
) -> List[Dict[str, Any]]:
    """Main flashcard generation pipeline."""
    del user_id
    card_count = target_count if target_count is not None else FINAL_COUNT_DEFAULT
    card_count = max(FLASHCARD_COUNT_MIN, min(FLASHCARD_COUNT_MAX, card_count))

    lecture = get_lecture(lecture_id)
    if not lecture:
        raise ValueError(f"Lecture {lecture_id} not found")
    if lecture[4] != "completed":
        raise ValueError(f"Lecture not ready for study materials (status: {lecture[4]})")

    key_points = get_lecture_key_points(lecture_id)
    if not key_points or len(key_points) < 3:
        try:
            generate_key_points_for_lecture(lecture_id)
            key_points = get_lecture_key_points(lecture_id)
        except Exception:
            pass

    use_chunks_fallback = not key_points or len(key_points) < 3
    existing_questions = []
    if regenerate:
        existing_questions = get_previous_flashcard_questions(lecture_id, limit_sets=3)

    chunks_per_keypoint: Optional[Dict[int, List[str]]] = None
    if not use_chunks_fallback and key_points:
        try:
            chunks_per_keypoint = get_chunks_per_keypoint(lecture_id, key_points, chunks_per_kp=2)
        except Exception:
            chunks_per_keypoint = None

    if use_chunks_fallback:
        chunks = prepare_context_for_chunks(lecture_id)
        candidates = generate_flashcards_from_chunks(chunks, existing_questions)
        key_points = []
    else:
        candidates = generate_flashcard_candidates(
            key_points,
            existing_questions,
            strategy=strategy,
            candidate_count=CANDIDATE_COUNT,
            chunks_per_keypoint=chunks_per_keypoint,
        )

    if not candidates:
        raise ValueError("No candidates generated by LLM")

    validated = []
    for candidate in candidates:
        if not _apply_validation_and_score(candidate, key_points):
            continue
        validated.append(candidate)

    dedup_against = [] if regenerate else existing_questions
    deduplicated = deduplicate_candidates(validated, dedup_against, embed_texts)

    max_per_keypoint = 2 if key_points and len(key_points) >= 5 else 3
    selected = select_final_flashcards(
        deduplicated,
        target_count=card_count,
        max_per_keypoint=max_per_keypoint,
    )

    if len(selected) < card_count and key_points:
        missing_count = card_count - len(selected)
        try:
            additional = fill_missing_flashcards(
                key_points,
                selected,
                missing_count * 3,
                chunks_per_keypoint=chunks_per_keypoint,
            )
            for candidate in additional:
                if _apply_validation_and_score(candidate, key_points):
                    selected.append(candidate)
                    if len(selected) >= card_count:
                        break
        except Exception:
            pass

    if len(selected) < card_count and key_points:
        _add_keypoint_fallback_cards(selected, key_points, existing_questions, card_count)

    selected_questions = {normalize_text(card.get("question", "")) for card in selected}
    if len(selected) < card_count and candidates:
        for candidate in candidates:
            if len(selected) >= card_count:
                break
            question = candidate.get("question", "")
            answer = candidate.get("answer", "")
            if normalize_text(question) in selected_questions:
                continue
            if not validate_flashcard_lenient(question, answer):
                continue
            _score_candidate(candidate, key_points)
            selected.append(candidate)
            selected_questions.add(normalize_text(question))

    if len(selected) == 0 and key_points:
        _add_ultimate_fallback_cards(selected, key_points, card_count)

    final = selected[:card_count]
    for card in final:
        keypoint_index = card.get("keypoint_index")
        if keypoint_index and key_points and 1 <= keypoint_index <= len(key_points):
            card["source_keypoint_id"] = keypoint_index - 1
        if card.get("source_ref"):
            card["source_chunk_ids"] = [card["source_ref"]]
    return final


def get_lecture_key_points(lecture_id: int) -> List[str]:
    """Get key points for a lecture."""
    materials = get_lecture_study_materials(lecture_id)
    if not materials:
        return []

    key_points: Any = materials.get("key_points", [])
    if isinstance(key_points, str):
        try:
            key_points = json.loads(key_points)
        except json.JSONDecodeError:
            return []
    return key_points if isinstance(key_points, list) else []


def _apply_validation_and_score(candidate: Dict[str, Any], key_points: List[str]) -> bool:
    is_valid, _ = validate_flashcard(
        candidate.get("question", ""),
        candidate.get("answer", ""),
    )
    if not is_valid:
        return False
    _score_candidate(candidate, key_points)
    return True


def _score_candidate(candidate: Dict[str, Any], key_points: List[str]) -> None:
    keypoint_index = candidate.get("keypoint_index")
    keypoint_text = None
    if key_points and keypoint_index and 1 <= keypoint_index <= len(key_points):
        keypoint_text = key_points[keypoint_index - 1]
    candidate["quality_score"] = compute_quality_score(
        candidate.get("question", ""),
        candidate.get("answer", ""),
        keypoint_text,
    )


def _add_keypoint_fallback_cards(
    selected: List[Dict[str, Any]],
    key_points: List[str],
    existing_questions: List[str],
    target_count: int,
) -> None:
    remaining = target_count - len(selected)
    normalized_existing = {normalize_text(question) for question in existing_questions}
    normalized_existing.update(normalize_text(card.get("question", "")) for card in selected)

    for index, key_point in enumerate(key_points, start=1):
        if remaining <= 0:
            break
        keypoint_text = (key_point or "").strip().rstrip(".")
        if not keypoint_text:
            continue
        lower_keypoint = keypoint_text.lower()
        if lower_keypoint.startswith(("how", "what", "why", "when", "where", "who", "which")):
            question = keypoint_text if keypoint_text.endswith("?") else f"{keypoint_text}?"
        else:
            question = f"What is {keypoint_text}?"
        if normalize_text(question) in normalized_existing:
            continue
        try:
            answer = expand_keypoint_to_answer(keypoint_text, question)
            if answer_echoes_question(question, answer):
                continue
        except Exception:
            answer = keypoint_text
        is_valid, _ = validate_flashcard(question, answer)
        if not is_valid:
            continue
        candidate = {
            "question": question,
            "answer": answer,
            "keypoint_index": index,
            "quality_score": compute_quality_score(question, answer, keypoint_text),
        }
        selected.append(candidate)
        normalized_existing.add(normalize_text(question))
        remaining -= 1


def _add_ultimate_fallback_cards(
    selected: List[Dict[str, Any]],
    key_points: List[str],
    target_count: int,
) -> None:
    for index, key_point in enumerate(key_points[:target_count], start=1):
        keypoint_text = (key_point or "").strip().rstrip(".")
        if not keypoint_text or len(keypoint_text.split()) < 2:
            continue
        question = f"What is {keypoint_text}?"
        answer = f"{keypoint_text}. It is a key concept for understanding the topic."
        if validate_flashcard_lenient(question, answer):
            selected.append(
                {
                    "question": question,
                    "answer": answer,
                    "keypoint_index": index,
                    "quality_score": 0.5,
                }
            )
